import type { Metadata } from "next";
import { ApolloWrapper } from "../graphql/lib/apollo-wrapper";
import ThemeProvider from "@/theme";
import { SettingsProvider } from "@/components/settings";
import { I18nextProvider } from 'react-i18next';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ApolloWrapper>
          <SettingsProvider defaultSettings={{ themeMode: "light" }}>
            <ThemeProvider>
              {children}
            </ThemeProvider>
          </SettingsProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
