# schema: "http://client-gateway-backend:3000/graphql"
schema: "https://grocery-api.nicolasfernandez.tech/graphql"
documents: "**/*.graphql"
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: .cache
