# schema: "http://client-gateway-backend:3000/graphql"
schema: "http://localhost:5400/graphql"
documents: "**/*.graphql"
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: .cache
