name: backend_client_gateway_ms_ci_cd_pipeline
on:
  push:
    branches:
      - "main"
    paths:
      - "backend/client-gateway/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "backend/client-gateway/**"
  workflow_dispatch:
env:
  #########################################
  #   GENERAL
  #########################################
  SHH_USER_PASSWORD: ${{secrets.SHH_USER_PASSWORD}}
  DOCKER_HUB_USERNAME: ${{vars.DOCKER_HUB_USERNAME}}
  DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
  DOCKER_IMAGE: ${{vars.DOCKER_HUB_USERNAME}}/${{vars.DOCKER_HUB_APP_IMAGE}}
  APP_NAME: ${{vars.APP_NAME}}

  #########################################
  #   ENVIRONMENT
  #########################################
  # Nest App
  BACKEND_CLIENT_GATEWAY_MS_DOCKER_IMAGE_VERSION: ${{vars.BACKEND_CLIENT_GATEWAY_MS_DOCKER_IMAGE_VERSION}}
  BACKEND_CLIENT_GATEWAY_MS_CONTAINER_NAME: ${{vars.BACKEND_CLIENT_GATEWAY_MS_CONTAINER_NAME}}
  BACKEND_CLIENT_GATEWAY_MS_HOST_PORT: ${{vars.BACKEND_CLIENT_GATEWAY_MS_HOST_PORT}}
  BACKEND_CLIENT_GATEWAY_MS_CONTAINER_PORT: ${{vars.BACKEND_CLIENT_GATEWAY_MS_CONTAINER_PORT}}
  CLIENT_GATEWAY_BACKEND_AUTHENTICATION_MS_HOST: ${{vars.CLIENT_GATEWAY_BACKEND_AUTHENTICATION_MS_HOST}}
  CLIENT_GATEWAY_BACKEND_PRODUCTS_MS_HOST: ${{vars.CLIENT_GATEWAY_BACKEND_PRODUCTS_MS_HOST}}
  BACKEND_NATS_TRANSPORTER_NETWORK: ${{vars.BACKEND_NATS_TRANSPORTER_NETWORK}}
jobs:
  retrieve-environment-variable:
    uses: ./.github/workflows/retrieve_environment.yml
  build-test-push-docker-image:
    name: Build, Test and Push Docker Image
    needs: retrieve-environment-variable
    runs-on: ubuntu-latest
    environment: ${{needs.retrieve-environment-variable.outputs.environment_name}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Build Docker Image
        run: docker build -t ${{env.DOCKER_IMAGE}}:${{env.BACKEND_CLIENT_GATEWAY_MS_DOCKER_IMAGE_VERSION}} --target=build ./backend/client-gateway

      - name: Build Docker Image Production
        run: docker build -t ${{env.DOCKER_IMAGE}}:${{env.BACKEND_CLIENT_GATEWAY_MS_DOCKER_IMAGE_VERSION}} ./backend/client-gateway

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKER_HUB_USERNAME}}
          password: ${{env.DOCKER_HUB_PASSWORD}}

      - name: Push to Dockerhub
        run: docker push ${{env.DOCKER_IMAGE}}:${{env.BACKEND_CLIENT_GATEWAY_MS_DOCKER_IMAGE_VERSION}}

  pull-backend-image-and-run-container:
    runs-on: self-hosted
    needs: [retrieve-environment-variable, build-test-push-docker-image]
    environment: ${{needs.retrieve-environment-variable.outputs.environment_name}}
    steps:
      - name: Network Creation
        run: echo ${{env.SHH_USER_PASSWORD}} | sudo -S docker network create ${{env.BACKEND_CLIENT_GATEWAY_MS_DOCKER_NETWORK}} || true

      - name: Stop Current Running Container
        run: echo ${{env.SHH_USER_PASSWORD}} | sudo -S docker rm -f ${{env.BACKEND_CLIENT_GATEWAY_MS_CONTAINER_NAME}} || true

      - name: Pull Docker Image
        run: echo ${{env.SHH_USER_PASSWORD}} | sudo -S docker pull ${{env.DOCKER_IMAGE}}:${{env.BACKEND_CLIENT_GATEWAY_MS_DOCKER_IMAGE_VERSION}}

      - name: Run Docker Container
        run: |
          echo ${{env.SHH_USER_PASSWORD}} | sudo -S docker run -d \
            --restart unless-stopped \
            -p ${{env.BACKEND_CLIENT_GATEWAY_MS_HOST_PORT}}:${{env.BACKEND_CLIENT_GATEWAY_MS_CONTAINER_PORT}} \
            -e CLIENT_GATEWAY_BACKEND_CONTAINER_PORT=${{env.BACKEND_CLIENT_GATEWAY_MS_CONTAINER_PORT}} \
            -e CLIENT_GATEWAY_BACKEND_HOST_PORT=${{env.BACKEND_CLIENT_GATEWAY_MS_HOST_PORT}} \
            -e CLIENT_GATEWAY_BACKEND_AUTHENTICATION_MS_HOST=${{env.CLIENT_GATEWAY_BACKEND_AUTHENTICATION_MS_HOST}} \
            -e CLIENT_GATEWAY_BACKEND_PRODUCTS_MS_HOST=${{env.CLIENT_GATEWAY_BACKEND_PRODUCTS_MS_HOST}} \
            --name ${{env.BACKEND_CLIENT_GATEWAY_MS_CONTAINER_NAME}} \
            --network ${{env.BACKEND_NATS_TRANSPORTER_NETWORK}} \
            ${{env.DOCKER_IMAGE}}:${{env.BACKEND_CLIENT_GATEWAY_MS_DOCKER_IMAGE_VERSION}}
