federation_version: 2
subgraphs:
  auth:
    routing_url: http://backend-authentication-ms-main:3000/graphql
    schema:
      introspection: true
  products:
    routing_url: http://backend-products-ms-main:3000/graphql
    schema:
      introspection: true